[ENV]
# Workspace is automatically the folder containing this TOML file.
# Only override if you want a different workspace root.
ZAP_DOWNLOADER_WORKSPACE = ""

# Subdirectories (optional, not used by the current code)
ZAP_DOWNLOADER_ZAP_HOME = ".zap"

[SERVER]
PORT = 8080
HOST = "0.0.0.0"

[PATHS]
# Relative to INSTALL_DIR
JAR_PATH = "zap/ZAP_2.17.0/zap-2.17.0.jar"

# Relative to the TOML directory
INSTALL_DIR = "install"

# ZAP home directory (relative to workspace)
DIR = ".zap"

[JAVA_OPTIONS]
flags = [
  "-Xms4g",
  "-Xmx4g",
  "-XX:+UseZGC",
  "-Xss512k",
  "-XX:MaxRAMPercentage=80",
  "-Dzap.session=/zap/wrk/session.data"
]

[CONFIG]
flags = [
  "api.disablekey=true",
  "api.addrs.addr.name=.*",
  "api.addrs.addr.regex=true",
  "database.response.bodysize=104857600",
  "database.cache.size=1000000",
  "database.recoverylog=false"
]