name: Dependencies Test - Node.js

on:
  workflow_dispatch:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Enable Corepack + pin pnpm
        run: |
          corepack enable
          corepack prepare pnpm@9.0.0 --activate
      
      - name: Install dependencies
        working-directory: apps
        run: pnpm install
      
      - name: Build
        working-directory: apps
        run: pnpm -r run build
      
      - name: Install Chrome
        run: pnpm offline:pack && pnpm offline:unpack && pnpm --filter @mockholm/zap-downloader ts-node src/index.ts dependencies chrome
      
      - name: Install Firefox
        run: pnpm --filter @mockholm/zap-downloader ts-node src/index.ts dependencies firefox
      
      - name: Verify Chrome
        run: pnpm verify:chrome
      
      - name: Verify Firefox
        run: pnpm verify:firefox

  windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        working-directory: apps
        run: pnpm install --no-frozen-lockfile
     
      - name: Build
        working-directory: apps
        run: pnpm -r run build
      
      - name: Install Chrome
        run: pnpm dependencies:chrome
      
      - name: Install Firefox
        run: pnpm dependencies:firefox
      
      - name: Verify Chrome
        run: pnpm verify:chrome
      
      - name: Verify Firefox
        run: pnpm verify:firefox
